In [3]:
import pandas as pd

In [4]:
dataset = pd.read_json("../dataset/memes.json")
dataset

,id,name,base_img,width,height,text_box,generated_memes
0,0,Drake Hotline Bling,https://i.imgflip.com/30b1gx.jpg,1200,1200,2,"[{'id': 1, 'alt_text': 'Drake Hotline Bling | ..."
1,1,Distracted Boyfriend,https://i.imgflip.com/1ur9b0.jpg,1200,800,3,"[{'id': 1, 'alt_text': 'Distracted Boyfriend |..."
2,2,Two Buttons,https://i.imgflip.com/1g8my4.jpg,600,908,2,"[{'id': 1, 'alt_text': 'Two Buttons | go buy r..."
3,3,Change My Mind,https://i.imgflip.com/24y43o.jpg,482,361,2,"[{'id': 1, 'alt_text': 'Change My Mind | Memes..."
4,4,Mocking Spongebob,https://i.imgflip.com/1otk96.jpg,502,353,2,"[{'id': 1, 'alt_text': 'Ugggggg | Upvote if yo..."
...,...,...,...,...,...,...,...
76,94,Marvel Civil War 1,https://i.imgflip.com/govs4.jpg,423,734,2,"[{'id': 1, 'alt_text': 'School: Civil War Trai..."
77,95,Philosoraptor,https://i.imgflip.com/1bgs.jpg,500,500,2,"[{'id': 1, 'alt_text': 'Philosoraptor | IF SAT..."
78,96,Me And The Boys,https://i.imgflip.com/320xfw.jpg,720,476,2,"[{'id': 1, 'alt_text': 'Me And The Boys | We j..."
79,98,I Should Buy A Boat Cat,https://i.imgflip.com/tau4.jpg,500,368,2,"[{'id': 1, 'alt_text': 'I Should Buy A Boat Ca..."
80,99,Sparta Leonidas,https://i.imgflip.com/46rh.jpg,500,264,2,"[{'id': 1, 'alt_text': 'Sparta Leonidas | MANK..."